import os

print("0 = blank")
print('y, x')
a = int(input("1,1 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
b = int(input("1,2 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
c = int(input("1,3 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
d = int(input("1,4 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
e = int(input("1,5 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
f = int(input("1,6 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
g = int(input("1,7 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
h = int(input("1,8 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
k = int(input("1,9 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
l = int(input("2,1 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
m = int(input("2,2 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
n = int(input("2,3 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
o = int(input("2,4 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
p = int(input("2,5 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
q = int(input("2,6 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
r = int(input("2,7 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
s = int(input("2,8 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
t = int(input("2,9 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
u = int(input("3,1 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
v = int(input("3,2 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
w = int(input("3,3 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
x = int(input("3,4 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
y = int(input("3,5 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
z = int(input("3,6 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
aa = int(input("3,7 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
bb = int(input("3,8 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
cc = int(input("3,9 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
dd = int(input("4,1 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
ee = int(input("4,2 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
ff = int(input("4,3 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
gg = int(input("4,4 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
hh = int(input("4,5 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
kk = int(input("4,6 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
ll = int(input("4,7 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
mm = int(input("4,8 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
nn = int(input("4,9 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
oo = int(input("5,1 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
pp = int(input("5,2 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
qq = int(input("5,3 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
rr = int(input("5,4 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
ss = int(input("5,5 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
tt = int(input("5,6 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
uu = int(input("5,7 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
vv = int(input("5,8 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
ww = int(input("5,9 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
xx = int(input("6,1 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
yy = int(input("6,2 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
zz = int(input("6,3 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
aaa = int(input("6,4 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
bbb = int(input("6,5 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
ccc = int(input("6,6 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
ddd = int(input("6,7 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
eee = int(input("6,8 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
fff = int(input("6,9 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
ggg = int(input("7,1 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
hhh = int(input("7,2 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
kkk = int(input("7,3 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
lll = int(input("7,4 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
mmm = int(input("7,5 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
nnn = int(input("7,6 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
ooo = int(input("7,7 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
ppp = int(input("7,8 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
qqq = int(input("7,9 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
rrr = int(input("8,1 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
sss = int(input("8,2 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
ttt = int(input("8,3 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
uuu = int(input("8,4 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
vvv = int(input("8,5 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
www = int(input("8,6 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
xxx = int(input("8,7 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
yyy = int(input("8,8 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
zzz = int(input("8,9 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
aaaa = int(input("9,1 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
bbbb = int(input("9,2 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
cccc = int(input("9,3 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
dddd = int(input("9,4 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
eeee = int(input("9,5 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
ffff = int(input("9,6 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
gggg = int(input("9,7 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
hhhh = int(input("9,8 Value: "))
os.system('clear')
os.system('cls')
print('y, x')
print("0 = blank")
kkkk = int(input("9,9 Value: "))
os.system('clear')
os.system('cls')

board = [
    [a,b,c,d,e,f,g,h,k],
    [l,m,n,o,p,q,r,s,t],
    [u,v,w,x,y,z,aa,bb,cc],
    [dd,ee,ff,gg,hh,kk,ll,mm,nn],
    [oo,pp,qq,rr,ss,tt,uu,vv,ww],
    [xx,yy,zz,aaa,bbb,ccc,ddd,eee,fff],
    [ggg,hhh,kkk,lll,mmm,nnn,ooo,ppp,qqq],
    [rrr,sss,ttt,uuu,vvv,www,xxx,yyy,zzz],
    [aaaa,bbbb,cccc,dddd,eeee,ffff,gggg,hhhh,kkkk]]


def solve(bo):
    find = find_empty(bo)
    if not find:
        return True
    else:
        row, col = find

    for i in range(1,10):
        if valid(bo, i, (row, col)):
            bo[row][col] = i

            if solve(bo):
                return True

            bo[row][col] = 0

    return False


def valid(bo, num, pos):
    # Check row
    for i in range(len(bo[0])):
        if bo[pos[0]][i] == num and pos[1] != i:
            return False

    # Check column
    for i in range(len(bo)):
        if bo[i][pos[1]] == num and pos[0] != i:
            return False

    # Check box
    box_x = pos[1] // 3
    box_y = pos[0] // 3

    for i in range(box_y*3, box_y*3 + 3):
        for j in range(box_x * 3, box_x*3 + 3):
            if bo[i][j] == num and (i,j) != pos:
                return False

    return True


def print_board(bo):
    for i in range(len(bo)):
        if i % 3 == 0 and i != 0:
            print("- - - - - - - - - - - - - ")

        for j in range(len(bo[0])):
            if j % 3 == 0 and j != 0:
                print(" | ", end="")

            if j == 8:
                print(bo[i][j])
            else:
                print(str(bo[i][j]) + " ", end="")


def find_empty(bo):
    for i in range(len(bo)):
        for j in range(len(bo[0])):
            if bo[i][j] == 0:
                return (i, j)  # row, col

    return None

print_board(board)
solve(board)
print("\n")
print_board(board)